name: add-fljtu-icon

on:
  push:
    paths:
      - '.github/workflows/add-fljtu-icon.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  icon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: write icon
        run: |
          if [ -f fljtu.png ]; then echo exists; exit 0; fi
          echo "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAYPSURBVHhe7dRLclhFEERRL4c1sWJ2BYMeKJwY/KkyuDtPRpyJbJVeT+6n337/40+g06f8AdBDAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYgIAxQQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYgIAxQQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYgIAxQQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAhBeX773FtPlPQ4BCK8v33uL6fIehwCE15fvvcV0eY9DAMLry/feYrq8xyEA4fXle28xXd7jEIDw+vK9t5gu73EIQHh9+d5bTJf3OAQgvL587y2my3scAhBeX773FtPlPQ4BCK8v33uL6fIehwCE15fvvcV0eY9DAMLry/feYrq8xyEA4fXle28xXd7jEIDw+vK9t5gu73EIQNhY3mRuurzHIQBhY3mTuenyHocAhI3lTeamy3scAhA2ljeZmy7vcQhA2FjeZG66vMchAGFjeZO56fIehwCEjeVN5qbLexwCEDaWN5mbLu9xCEDYWN5kbrq8xyEAYWN5k7np8h6HAISN5U3mpst7HAIQNpY3mZsu73EIQNhY3mRuurzHIQBhY3mTuenyHocAhI3lTeamy3scAhA2ljeZmy7vcQhA2FjeZG66vMchAGFjeZO56fIehwCEjeVN5qbLexwCEF5avu1m0+U9DgEILy3fdrPp8h6HAISXlm+72XR5j0MAwkvLt91surzHIQDhpeXbbjZd3uMQgPDS8m03my7vcQhAeGn5tptNl/c4BCC8tHzbzabLexwCEF5avu1m0+U9DgEILy3fdrPp8h6HAISXlm+72XR5j0MAwkvLt91surzHIQDhpeXbbjZd3uMQgPDS8m03my7vcQhA2FjeZG66vMchAGFjeZO56fIehwCEjeVN5qbLexwCEDaWN5mbLu9xCEDYWN5kbrq8xyEAYWN5k7np8h6HAISN5U3mpst7HAIQNpY3mZsu73EIQNhY3nxdLv99w3R5j0MAwsby5u2+d/n7G6bLexwCEDaWN280Xd6bmi7vcQhA2FjevNF0eW9qurzHIQBhY3nzRtPlvYmN5U0OAQgby5s3mi7vTWwsb3IIQNhY3rzRdHlvYmN5k0MAwsby5o2my3sTG8ubHAIQNpY3b7SxvPmjpst7fBCAsLG8eavp8t6P2Fje5IMAhI3lzVttLG9+r43lTT4IQNhY3rzV1vLut9pa3uWDAISN5c1bbS5vf83m8jYfBCBsLG/eant5/59sLm/zOQEIG8ubN7t9+R4+JwBhY3nzZjcv38LfCUDYWN683a3Ld/B3AhA2ljdvd+PyDXyZAISN5c0X3Lb8fr5MAMLG8uYrbll+N/9MAMLG8uYrblh+M/9OAMLG8uZLfuXlt/J1AhA2ljdf8ysuv5FvIwBhY3nzRb/S8tv4dgIQNpY3X/Z/Lr+F7ycAYWN583X/x/Ib+DECEDaWN1v87OXfY04A+Gm2lnfZIwD85760/D/8NwQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYgIAxQQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYgIAxQQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYgIAxQQAigkAFBMAKCYAUEwAoJgAQDEBgGICAMUEAIoJABQTACgmAFBMAKCYAEAxAYBiAgDFBACKCQAUEwAoJgBQTACgmABAMQGAYn8Bh1GTYHRV23MAAAAASUVORK5CYII=" | base64 -d > fljtu.png
          git config user.name github-actions
          git config user.email actions@github.com
          git add fljtu.png
          git commit -m "Add fljtu icon"
          git push

